DROP TABLE IF EXISTS names;

CREATE TABLE IF NOT EXISTS names (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE,
	owner TEXT NOT NULL UNIQUE,
	texts TEXT,
	addresses TEXT,
	contenthash TEXT,
	rejected TEXT CHECK(rejected IN ('true', 'false')) DEFAULT 'false',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS admins;

CREATE TABLE IF NOT EXISTS admins (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	address TEXT UNIQUE NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);